import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setTimeout as delay} from 'node:timers/promises';
import {JSDOM} from 'jsdom';
import {openSheetDocument,parseCsv} from '../dist/sheet-document.mjs';
import {mountSingleEditor,singleSheetMetadata} from '../dist/single-editor.mjs';
import {mountSheetReview} from '../dist/sheet-review.mjs';
import {findTextMatches,replacementPatches} from '../dist/find-replace.mjs';
import {read,write,utils,CFB} from '../dist/xlsx-vendor.mjs';
import {handleRequest} from '../dist/worker.mjs';
import {validateSinglePayload} from '../dist/single-session.mjs';
const source=(name,bytes)=>({name,data:Buffer.from(bytes).toString('base64')});
const until=async fn=>{for(let i=0;i<400;i++){if(fn())return;await delay(10);}assert.fail('Timed out');};
function setup(t){const dom=new JSDOM('<main></main>',{pretendToBeVisual:true});Object.assign(globalThis,{window:dom.window,document:dom.window.document});window.Element.prototype.scrollIntoView=()=>{};const root=document.querySelector('main'),downloads=[];const oldCreate=URL.createObjectURL,oldRevoke=URL.revokeObjectURL;URL.createObjectURL=b=>{downloads.push(b);return 'blob:table';};URL.revokeObjectURL=()=>{};window.HTMLAnchorElement.prototype.click=()=>{};t.after(()=>{dom.window.close();delete globalThis.window;delete globalThis.document;URL.createObjectURL=oldCreate;URL.revokeObjectURL=oldRevoke;});return {root,downloads};}
function finder(root){root.querySelector('.document-find>button').click();const panel=root.querySelector('.find-replace-panel');return {panel,query:panel.querySelector('[data-find-field="query"]'),replacement:panel.querySelector('[data-find-field="replacement"]'),button:label=>[...panel.querySelectorAll('button')].find(b=>b.textContent===label),async search(text){this.query.value=text;this.query.dispatchEvent(new window.Event('input'));await until(()=>!this.button('Replace').disabled);},replaceWith(text){this.replacement.value=text;this.replacement.dispatchEvent(new window.Event('input'));}};}
function fixture(){const wb=utils.book_new(),ws=utils.aoa_to_sheet([['sku','supplier','amount','date','active'],['001','Vendor Vendor',10,45000,true],['002','Vendor',20,45001,false]],{origin:'C3'});ws.C4.z='@';ws.E4.z='0.00';ws.F4.z='yyyy-mm-dd';utils.book_append_sheet(wb,ws,'Orders');utils.book_append_sheet(wb,utils.aoa_to_sheet([['Vendor'],[{t:'n',v:4,f:'2+2'}]]),'Other');return source('orders.xlsx',write(wb,{type:'array',bookType:'xlsx',compression:true}));}
test('sheet text batch preserves types, leading zeros, inserted rows, formatting and unrelated workbook parts',async()=>{
 const src=fixture(),meta=await singleSheetMetadata(src,{sheet:'Orders'}),doc=await openSheetDocument(src,meta,',');assert.equal(doc.textEntries().some(e=>e.key==='E4'||e.key==='F4'||e.key==='G4'),false);assert.ok(doc.textEntries().some(e=>e.key==='C3'));
 doc.insertRow(4,[['C5',{t:'s',v:'003'}],['D5',{t:'s',v:'Vendor'}]]);const before=doc.snapshot(),entries=doc.textEntries(),hits=findTextMatches(entries,'Vendor');assert.equal(hits.length,4);doc.updateTexts(replacementPatches(entries,hits,'Acme'));assert.equal(doc.get('D4').v,'Acme Acme');assert.equal(doc.get('D5').v,'Acme');assert.deepEqual(doc.snapshot().insertions,before.insertions);
 const output=doc.export(),book=read(output,{type:'array',cellNF:true});assert.equal(book.Sheets.Orders.C4.v,'001');assert.equal(book.Sheets.Orders.C4.t,'s');assert.equal(book.Sheets.Orders.C4.z,'@');assert.equal(book.Sheets.Orders.E4.v,10);assert.equal(book.Sheets.Orders.E4.z,'0.00');assert.equal(book.Sheets.Orders.F4.v,45000);assert.equal(book.Sheets.Orders.F4.z,'yyyy-mm-dd');assert.equal(book.Sheets.Orders.G4.t,'b');assert.equal(book.Sheets.Other.A1.v,'Vendor');assert.equal(book.Sheets.Other.A2.f,'2+2');doc.undo();assert.deepEqual(doc.snapshot(),before);
 const stable=doc.snapshot();assert.throws(()=>doc.updateTexts([{index:0,key:'C3',before:'sku',text:'x'.repeat(131073)}]),/invalid/);assert.deepEqual(doc.snapshot(),stable);
 // Without row insertion, only the edited sheet and calculation flag may change.
 const plain=await openSheetDocument(src,meta,','),list=plain.textEntries();plain.updateTexts(replacementPatches(list,findTextMatches(list,'Vendor'),'0012'));const a=CFB.read(Buffer.from(src.data,'base64'),{type:'array'}),b=CFB.read(plain.export(),{type:'array'});for(let i=0;i<a.FullPaths.length;i++){const name=a.FullPaths[i];if(a.FileIndex[i].type!==2||name.endsWith('worksheets/sheet1.xml')||name.endsWith('xl/workbook.xml')||name.endsWith('\u0001Sh33tJ5'))continue;assert.deepEqual(new Uint8Array(CFB.find(b,name).content),new Uint8Array(a.FileIndex[i].content),name);}assert.equal(read(plain.export(),{type:'array'}).Sheets.Orders.D5.t,'s');
});
test('CSV search reaches offscreen cells, commits pending text, saves replacement and restores one-step undo',async t=>{
 const {root,downloads}=setup(t),src=source('orders.csv','\ufeffsku;note\r\n'+Array.from({length:65},(_,i)=>`00${i};${i===59?'Vendor Vendor':i===64?'Vendor':'unchanged'}`).join('\r\n')+'\r\n');let view,saved;view=await mountSingleEditor(root,{source:src,delimiter:';',onStateChange:()=>{saved=view.snapshot();}});t.after(()=>view.dispose());root.querySelector('[data-cell="B2"]').click();const input=root.querySelector('[data-edit-side="left"]');input.value='Vendor pending';input.dispatchEvent(new window.Event('input'));const find=finder(root);await find.search('Vendor');assert.match(find.panel.textContent,/1 of 4/);assert.equal(root.querySelector('[data-cell="B2"]').textContent,'Vendor pending');find.button('Next').click();await until(()=>root.querySelector('[data-cell="B61"]')?.classList.contains('is-search-current'));assert.match(find.panel.querySelector('.find-replace-preview').textContent,/B61/);assert.equal(root.querySelector('[data-edit-side="left"]').selectionStart,0);find.button('Next').click();await until(()=>root.querySelector('[data-edit-side="left"]').selectionStart===7);
 const before=view.snapshot();find.replaceWith('Supplier');find.button('Replace all').click();await until(()=>/Replaced 4/.test(find.panel.textContent));assert.equal(view.snapshot().undo.length,before.undo.length+1);const payload=validateSinglePayload({version:1,kind:'single-editor',source:src,sheet:null,delimiter:';',review:saved});root.querySelector('[data-save-side="left"]').click();await until(()=>downloads.length===1);const blob=downloads.pop(),bytes=new Uint8Array(await blob.arrayBuffer());assert.deepEqual([...bytes.slice(0,3)],[239,187,191]);const rows=parseCsv(await blob.text(),';');assert.equal(rows[1][0],'000');assert.equal(rows[1][1],'Supplier pending');assert.equal(rows[60][1],'Supplier Supplier');assert.equal(rows[65][1],'Supplier');
 view.dispose();view=await mountSingleEditor(root,{source:src,delimiter:';',restoredState:payload.review});const restored=finder(root);restored.button('Undo').click();await until(()=>view.snapshot().undo.length===before.undo.length);assert.deepEqual(view.snapshot().drafts,before.drafts);assert.ok(view.snapshot().drafts.left.patches.some(([a,c])=>a==='B2'&&c.v==='Vendor pending'),'Undo keeps the earlier manual input');
});
test('spreadsheet search rejects invalid pending input and changes only the selected comparison side',async t=>{
 const {root}=setup(t),left=source('a.csv','sku,note,extra\n001,Vendor,Vendor\n'),right=source('b.csv','sku,note,extra\n001,Vendor,Vendor\n');const {report}=await handleRequest('/api/compare',{left,right,key:['sku','sku'],fields:[['note','note','text']],delimiter:',',strip:false});let view=await mountSheetReview(root,{report,sources:{left,right}});t.after(()=>view.dispose());root.querySelector('[data-side="left"][data-cell="B2"]').click();const input=root.querySelector('[data-edit-side="right"]'),type=root.querySelector('[aria-label="Cell type in B"]');input.value='-';type.value='number';const find=finder(root);find.query.value='Vendor';find.query.dispatchEvent(new window.Event('input'));assert.match(find.panel.textContent,/Apply or undo/);assert.equal(input.value,'-');assert.equal(find.button('Replace').disabled,true);assert.equal(view.snapshot().drafts.right.patches.length,0);
 input.value='Vendor pending';type.value='text';await find.search('Vendor');assert.match(find.panel.textContent,/of 2/);find.replaceWith('New');find.button('Replace all').click();await until(()=>/Replaced 2/.test(find.panel.textContent));assert.equal(root.querySelector('[data-side="right"][data-cell="C2"]').textContent,'New','Unchecked columns are included');assert.equal(root.querySelector('[data-side="left"][data-cell="B2"]').textContent,'Vendor');const scope=find.panel.querySelector('select');scope.value='left';scope.dispatchEvent(new window.Event('change'));await until(()=>!find.button('Replace').disabled);find.replaceWith('Other');find.button('Replace').click();await until(()=>/Replaced 1/.test(find.panel.textContent));assert.equal(root.querySelector('[data-side="left"][data-cell="B2"]').textContent,'Other');assert.equal(root.querySelector('[data-side="right"][data-cell="B2"]').textContent,'New pending');
});
