import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Script,SyntheticModule} from 'node:vm';
import {PDFDocument,fontkit} from '../dist/pdf-vendor.mjs';
import fontBase64 from '../dist/pdf-font.mjs';
import {readTextSource} from '../dist/text-source.mjs';
import {openPdfVisual,planPdfEdits,measurePdfFont} from '../dist/pdf-visual.mjs';
import {mountSingleSession,validateSinglePayload} from '../dist/single-session.mjs';
import {setTimeout as delay} from 'node:timers/promises';
import {JSDOM} from 'jsdom';
import {createRequire} from 'node:module';
import {inspectSingleSource,singleSheetMetadata,mountSingleEditor} from '../dist/single-editor.mjs';
import {mountVisualReview} from '../dist/visual-review.mjs';
import {readDocxVisual} from '../dist/docx-visual.mjs';
import {read,write,utils} from '../dist/xlsx-vendor.mjs';
import {getDocument} from '../dist/pdf-reader-vendor.mjs';
import editor from '../dist/text-editor.js';
const require=createRequire(import.meta.url),native=require('@napi-rs/canvas');
const source=(name,data)=>({name,data:Buffer.from(data).toString('base64')});
const until=async fn=>{for(let i=0;i<400;i++){if(fn())return;await delay(15);}assert.fail('Timed out');};
const visible=n=>!n.closest('[hidden]');
async function textPdf(blob){const task=getDocument({data:new Uint8Array(await blob.arrayBuffer()),isEvalSupported:false,disableFontFace:true,verbosity:0});try{const doc=await task.promise;let text='';for(let i=1;i<=doc.numPages;i++)text+=(await (await doc.getPage(i)).getTextContent()).items.map(x=>x.str).join(' ');return text;}finally{await task.destroy();}}
function setup(t,html='<main></main>'){
 const dom=new JSDOM(html,{url:'https://ctt.example/',pretendToBeVisual:true,runScripts:'outside-only'});Object.assign(globalThis,{window:dom.window,document:dom.window.document,DOMMatrix:native.DOMMatrix,Path2D:native.Path2D,ImageData:native.ImageData});window.KristinaTextEditor=editor;window.Element.prototype.scrollIntoView=()=>{};
 const canvases=new WeakMap(),canvas=el=>{let c=canvases.get(el);if(!c||c.width!==el.width||c.height!==el.height){c=native.createCanvas(el.width,el.height);canvases.set(el,c);}return c;};window.HTMLCanvasElement.prototype.getContext=function(type){const ctx=canvas(this).getContext(type);if(!ctx.wrapped){const draw=ctx.drawImage.bind(ctx);ctx.drawImage=(img,...a)=>draw(img instanceof window.HTMLCanvasElement?canvas(img):img,...a);ctx.wrapped=true;}return ctx;};
 window.HTMLCanvasElement.prototype.toBlob=function(callback,mime){canvas(this).toBlob(callback,mime);};
 globalThis.FontFace=class{constructor(name,bytes){this.name=name;this.bytes=bytes;}async load(){native.GlobalFonts.register(Buffer.from(this.bytes),this.name);return this;}};document.fonts={add(){}};
 const downloads=[],names=[],oldCreate=URL.createObjectURL,oldRevoke=URL.revokeObjectURL;URL.createObjectURL=b=>{downloads.push(b);return 'blob:single';};URL.revokeObjectURL=()=>{};window.HTMLAnchorElement.prototype.click=function(){names.push(this.download);};
 t.after(()=>{dom.window.close();URL.createObjectURL=oldCreate;URL.revokeObjectURL=oldRevoke;for(const k of ['window','document','DOMMatrix','Path2D','ImageData','FontFace'])delete globalThis[k];});return {dom,root:document.querySelector('main'),downloads,names};
}
function fixtureBook(){const book=utils.book_new();utils.book_append_sheet(book,utils.aoa_to_sheet([['Unchanged'],[{t:'n',v:4,f:'2+2'}]]),'Other');const sheet=utils.aoa_to_sheet([['001',10],['002',20]],{origin:'C3'});utils.book_append_sheet(book,sheet,'Orders');return source('orders.xlsx',write(book,{type:'array',bookType:'xlsx',compression:true}));}
test('single imports accept duplicate/headerless CSV, choose worksheet and reject unsafe sheet layouts',async()=>{
 assert.equal((await inspectSingleSource(source('file.csv','x;x\n001;002'))).delimiter,';');
 await singleSheetMetadata(source('file.csv','x,x\n001,002'));
 const src=fixtureBook();assert.deepEqual((await inspectSingleSource(src)).sheets,['Other','Orders']);assert.equal((await singleSheetMetadata(src,{sheet:'Orders'})).sheet,'Orders');assert.equal((await singleSheetMetadata(src,{sheet:'Other'})).sheet,'Other');
 await assert.rejects(()=>singleSheetMetadata(source('large.csv',Array(200000).fill('x').join('\n'))),/5,000/);await assert.rejects(()=>mountSingleEditor(null,{source:source('file.pdf','pdf')}),/signature/);
});
test('standalone Word edits text with tables and images, exports original format and the same edited PDF',async t=>{
 const {root,downloads,names}=setup(t),demo=await readFile(new URL('../dist/document-demo.js',import.meta.url),'utf8'),src=JSON.parse(demo.slice(demo.indexOf('Object.freeze(')+14,demo.lastIndexOf(');'))).right;
 const view=await mountSingleEditor(root,{source:src});t.after(()=>view.dispose());assert.equal([...root.querySelectorAll('.visual-column')].filter(visible).length,1);assert.equal([...root.querySelectorAll('[data-copy-to]')].filter(visible).length,0);
 const paragraph=[...root.querySelectorAll('.visual-column:not([hidden]) [data-group]')].find(n=>n.textContent.includes('Warranty'));paragraph.click();const input=root.querySelector('[data-edit-side="left"]');input.value='Warranty: 48 months.';input.dispatchEvent(new window.Event('input'));
 assert.ok(view.changed);assert.equal(root.querySelectorAll('.has-difference').length,0);
 root.querySelector('[data-save-side="left"]').click();await until(()=>downloads.length===1);const saved=await readDocxVisual(source('edited.docx',await downloads[0].arrayBuffer()));assert.ok(saved.blocks.some(b=>b.text==='Warranty: 48 months.'));assert.ok(saved.blocks.some(b=>b.runs.some(r=>r.image)));assert.match(names[0],/-edited.docx$/);
 root.querySelector('[data-download-format="left"]').value='pdf';root.querySelector('[data-save-side="left"]').click();await until(()=>root.querySelector('.document-pdf-dialog .primary')?.disabled===false);root.querySelector('.document-pdf-dialog .primary').click();assert.match(await textPdf(downloads[1]),/Warranty: 48 months/);
 root.querySelector('.document-pdf-dialog .secondary').click();root.querySelector('[aria-label="Undo edit"]').click();assert.equal(view.changed,false);
});
test('single-sheet pending input survives cell selection, undo, original export and PDF',async t=>{
 const {root,downloads}=setup(t),src=fixtureBook(),view=await mountSingleEditor(root,{source:src,sheet:'Orders'});t.after(()=>view.dispose());assert.equal([...root.querySelectorAll('.visual-column')].filter(visible).length,1);assert.equal([...root.querySelectorAll('[data-review-action]')].filter(visible).length,0);
 root.querySelector('[data-side="left"][data-cell="D4"]').click();root.querySelector('[data-edit-side="left"]').value='25';assert.ok(view.changed);root.querySelector('[data-side="left"][data-cell="C4"]').click();assert.equal(root.querySelector('[data-side="left"][data-cell="D4"]').textContent,'25');
 const field=root.querySelector('[data-edit-side="left"]');field.value='008';field.dispatchEvent(new window.Event('input'));root.querySelector('[data-sheet-undo]').click();assert.equal(field.value,'002');assert.equal(root.querySelector('[data-side="left"][data-cell="D4"]').textContent,'25');field.value='009';root.querySelector('[data-save-side="left"]').click();await until(()=>downloads.length===1);const book=read(new Uint8Array(await downloads[0].arrayBuffer()),{type:'array'});assert.equal(book.Sheets.Orders.C4.v,'009');assert.equal(book.Sheets.Orders.D4.v,25);assert.equal(book.Sheets.Other.A2.f,'2+2');
 root.querySelector('[data-download-format="left"]').value='pdf';root.querySelector('[data-save-side="left"]').click();await until(()=>root.querySelector('.document-pdf-dialog .primary')?.disabled===false);root.querySelector('.document-pdf-dialog .primary').click();const text=await textPdf(downloads[1]);assert.match(text,/009/);assert.match(text,/25/);assert.doesNotMatch(text,/Unchanged/);
 root.querySelector('.document-pdf-dialog .secondary').click();root.querySelector('[data-sheet-undo]').click();assert.equal(root.querySelector('[data-side="left"][data-cell="C4"]').textContent,'002');
});
test('real mode switch opens one CSV, retains work on mode changes and keeps it after failed replacement',async t=>{
 const html=await readFile(new URL('../dist/index.html',import.meta.url),'utf8'),{dom,downloads}=setup(t,html);Object.defineProperty(document,'currentScript',{value:{src:'https://ctt.example/single-entry.js'},configurable:true});
 const script=new Script(await readFile(new URL('../dist/single-entry.js',import.meta.url),'utf8'),{importModuleDynamically:specifier=>specifier.endsWith('single-session.mjs')?import('../dist/single-session.mjs'):import('../dist/single-editor.mjs')});script.runInContext(dom.getInternalVMContext());
 document.querySelector('[data-work-mode="single"]').click();assert.equal(document.getElementById('single-workspace').hidden,false);assert.equal(document.getElementById('compare-workspace').hidden,true);
 async function load(name,text){const file={name,size:Buffer.byteLength(text),arrayBuffer:async()=>new TextEncoder().encode(text).buffer},field=document.getElementById('single-file');Object.defineProperty(field,'files',{value:[file],configurable:true});field.dispatchEvent(new window.Event('change'));}
 await load('one.csv','001;10\n002;20');await until(()=>!document.getElementById('single-options').hidden);assert.equal(document.getElementById('single-delimiter').value,';');document.getElementById('single-open').click();await until(()=>document.querySelector('#single-editor-host [data-cell="B2"]'));
 document.querySelector('[data-side="left"][data-cell="B2"]').click();document.querySelector('[data-edit-side="left"]').value='35';document.querySelector('[data-work-mode="compare"]').click();document.querySelector('[data-work-mode="single"]').click();assert.equal(document.querySelector('[data-edit-side="left"]').value,'35');
 document.querySelector('[data-save-side="left"]').click();await until(()=>downloads.length===1);assert.equal(await downloads[0].text(),'001;10\n002;35');window.confirm=()=>true;
 await load('bad.docx','not a zip');await until(()=>/zip|archive|Word|DOCX/i.test(document.getElementById('single-notice').textContent));assert.ok(document.querySelector('#single-editor-host [data-cell="B2"]'));assert.equal(document.getElementById('single-current').textContent,'one.csv');
 const notice=document.getElementById('single-notice');assert.ok(notice.classList.contains('error'));assert.equal(notice.getAttribute('role'),'alert');
 await load('bad.pdf','not a PDF');await until(()=>/signature/i.test(notice.textContent));assert.ok(notice.classList.contains('error'));assert.equal(notice.getAttribute('role'),'alert');
 await load('replacement.csv','003;30');await until(()=>!document.getElementById('single-options').hidden);assert.equal(notice.classList.contains('error'),false);assert.equal(notice.getAttribute('role'),'status');assert.ok(notice.hidden);
 const cached=new window.Event('pagehide');Object.defineProperty(cached,'persisted',{value:true});window.dispatchEvent(cached);assert.ok(document.querySelector('#single-editor-host [data-cell="B2"]'));const ids=[...document.querySelectorAll('[id]')].map(n=>n.id);assert.equal(ids.length,new Set(ids).size);window.dispatchEvent(new window.Event('pagehide'));
});


test('single PDF entry restores edits, block geometry and view, then downloads with its image',async t=>{
 const doc=await PDFDocument.create();doc.registerFontkit(fontkit);const font=await doc.embedFont(Buffer.from(fontBase64,'base64'),{subset:true});
 const page=doc.addPage([400,500]);page.drawText('Original name',{x:40,y:440,size:14,font});page.drawText('Original paragraph.',{x:40,y:360,size:12,font});
 const photo=native.createCanvas(80,40),ctx=photo.getContext('2d');ctx.fillStyle='#e02040';ctx.fillRect(0,0,80,40);const image=await doc.embedPng(photo.toBuffer('image/png'));page.drawImage(image,{x:40,y:160,width:80,height:40});
 doc.addPage([400,500]).drawText('Unchanged second page.',{x:40,y:440,size:14,font});const bytes=await doc.save();
 let saved={token:null,payload:null},serial=0;const store={read:async()=>structuredClone(saved),async write(payload,token){assert.equal(token,saved.token);saved={token:String(++serial),payload:validateSinglePayload(payload)};return structuredClone(saved);},async clear(token){assert.equal(token,saved.token);saved={token:String(++serial),payload:null};return structuredClone(saved);},close(){}};
 async function openEntry(){
  const env=setup(t,await readFile(new URL('../dist/index.html',import.meta.url),'utf8')),context=env.dom.getInternalVMContext();Object.defineProperty(document,'currentScript',{value:{src:'https://ctt.example/single-entry.js'},configurable:true});
  const module=new SyntheticModule(['mountSingleSession'],function(){this.setExport('mountSingleSession',(root,options)=>mountSingleSession(root,{...options,openStore:async()=>store}));},{context});await module.link(()=>{});await module.evaluate();
  new Script(await readFile(new URL('../dist/single-entry.js',import.meta.url),'utf8'),{importModuleDynamically:specifier=>specifier.endsWith('single-session.mjs')?module:import('../dist/single-editor.mjs')}).runInContext(context);
  env.$=id=>document.getElementById(id);await until(()=>env.$('single-session-status'));env.host=env.$('single-editor-host');return env;
 }
 let env=await openEntry();window.confirm=()=>true;document.querySelector('[data-work-mode="single"]').click();
 assert.ok(env.$('single-file').accept.includes('.pdf'));
 async function upload(name,data){const field=env.$('single-file');Object.defineProperty(field,'files',{value:[{name,size:data.length,arrayBuffer:async()=>data.slice().buffer}],configurable:true});field.dispatchEvent(new window.Event('change'));}
 await upload('document.pdf',bytes);await until(()=>env.host.querySelector('canvas')&&!env.host.querySelector('[data-save-side="left"]').disabled);
 assert.equal(env.$('single-options').hidden,true);assert.equal([...env.host.querySelectorAll('.visual-column')].filter(visible).length,1);assert.equal(env.host.querySelectorAll('canvas').length,1);assert.equal([...env.host.querySelectorAll('[data-copy-to]')].filter(visible).length,0);
 // Original bytes remain available before any edit.
 env.host.querySelector('[data-save-side="left"]').click();await until(()=>env.downloads.length===1);assert.deepEqual(new Uint8Array(await env.downloads.pop().arrayBuffer()),bytes);
 env.host.querySelector('.visual-hotspot').click();await until(()=>!env.host.querySelector('[data-replace-block="left"]').hidden);env.host.querySelector('[data-replace-block="left"]').click();
 const modal=()=>env.host.querySelector('.pdf-block-dialog'),apply=()=>modal()?.querySelector('.pdf-block-actions .primary');await until(()=>apply()&&!apply().disabled);
 modal().querySelector('textarea').value='Alexandra Montgomery';modal().querySelector('[aria-label="Width in points"]').value='260';modal().querySelector('textarea').dispatchEvent(new window.Event('input'));await until(()=>!apply().disabled);apply().click();
 await until(()=>/Saved in this browser/.test(env.$('single-session-status').textContent)&&!env.host.querySelector('[data-save-side="left"]').disabled);
 const blockState=structuredClone(saved.payload.review.drafts.left);assert.match(JSON.stringify(blockState),/Alexandra Montgomery/);assert.match(JSON.stringify(blockState),/pdfBox/);
 env.host.querySelector('[aria-label="Next page"]').click();await until(()=>saved.payload.review.pages.left===2);env.host.querySelector('[data-pdf-text-view="left"]').click();await until(()=>saved.payload.review.pdfTextView===true);
 window.dispatchEvent(new window.Event('pagehide'));await delay(50);env.dom.window.close();
 env=await openEntry();assert.match(env.$('single-session').textContent,/document.pdf/);env.$('single-session-resume').click();await until(()=>env.host.querySelector('[data-pdf-text-view="left"]')?.getAttribute('aria-pressed')==='true'&&!env.host.querySelector('[data-save-side="left"]').disabled);
 assert.equal(env.$('single-workspace').hidden,false);assert.deepEqual(saved.payload.review.drafts.left,blockState);assert.equal(saved.payload.review.pages.left,2);
 env.host.querySelector('[data-pdf-preview="left"]').click();await until(()=>env.host.querySelector('canvas')&&env.host.querySelector('[data-pdf-view="left"]').getAttribute('aria-pressed')==='true');assert.match(env.host.querySelector('.visual-page-nav').textContent,/2 \/ 2/);
 env.host.querySelector('[data-save-side="left"]').click();await until(()=>env.downloads.length===1);const output=source('edited.pdf',new Uint8Array(await env.downloads.pop().arrayBuffer())),text=(await readTextSource(output)).blocks.map(b=>b.text).join(' ');assert.match(text,/Alexandra Montgomery/);assert.doesNotMatch(text,/Original name/);assert.match(text,/Unchanged second page/);
 const viewer=await openPdfVisual(output),canvas=document.createElement('canvas');await viewer.renderPage(1,canvas);await viewer.dispose();const pixels=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let red=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i]>190&&pixels[i+1]<60&&pixels[i+2]>40&&pixels[i+2]<100)red++;assert.ok(red>2800,'The image survives single PDF edit/export');
 // A rejected scan leaves the current PDF and saved edits intact.
 window.confirm=()=>true;const scan=await PDFDocument.create();scan.addPage([400,500]);await upload('scan.pdf',await scan.save());await until(()=>/text|scan/i.test(env.$('single-notice').textContent)&&!env.$('single-file').disabled);assert.equal(saved.payload.source.name,'document.pdf');assert.deepEqual(saved.payload.review.drafts.left,blockState);
 env.host.querySelector('[aria-label="Undo edit"]').click();await until(()=>!env.host.querySelector('[data-save-side="left"]').disabled);env.host.querySelector('[data-save-side="left"]').click();await until(()=>env.downloads.length===1);assert.deepEqual(new Uint8Array(await env.downloads.pop().arrayBuffer()),bytes,'Undo restores original PDF bytes');
 // Long typing uses the image-preserving layout and can be restored on generated pages.
 env.host.querySelector('[data-pdf-text-view="left"]').click();await until(()=>env.host.querySelector('[data-group="text:2"].visual-paragraph'));env.host.querySelector('[data-group="text:2"].visual-paragraph').click();const field=env.host.querySelector('[data-edit-side="left"]');field.value=Array.from({length:45},(_,i)=>`Expanded line ${i+1}`).join('\n');field.dispatchEvent(new window.Event('input'));await until(()=>!env.host.querySelector('[data-save-side="left"]').disabled);env.host.querySelector('[data-pdf-preview="left"]').click();await until(()=>env.host.querySelector('[data-pdf-layout="updated"]'));
 env.host.querySelector('[aria-label="Next page"]').click();await until(()=>saved.payload.review.pages.left===2);const checkpoint=validateSinglePayload(saved.payload),extra=document.createElement('div');const resumed=await mountSingleEditor(extra,{source:checkpoint.source,restoredState:checkpoint.review});assert.equal(resumed.snapshot().pages.left,2);assert.ok(extra.querySelector('[data-pdf-layout="updated"]'));resumed.dispose();
 env.host.querySelector('[data-save-side="left"]').click();await until(()=>env.downloads.length===1);const expanded=source('expanded.pdf',new Uint8Array(await env.downloads.pop().arrayBuffer()));assert.match(await textPdf(new Blob([Buffer.from(expanded.data,'base64')])),/Expanded line 45/);const expandedViewer=await openPdfVisual(expanded);let imagePages=0;for(let n=1;n<=expandedViewer.pageCount;n++){const c=document.createElement('canvas');await expandedViewer.renderPage(n,c);const px=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let red=0;for(let i=0;i<px.length;i+=4)if(px[i]>190&&px[i+1]<60&&px[i+2]>40&&px[i+2]<100)red++;if(red>2800)imagePages++;}await expandedViewer.dispose();assert.equal(imagePages,1,'The complete image survives expanded layout on exactly one page');
 env.$('single-session-delete').click();await until(()=>!env.host.children.length);assert.equal(saved.payload,null);window.dispatchEvent(new window.Event('pagehide'));await delay(30);assert.equal(saved.payload,null);
});


test('inline name fitting retains flattened artwork, text layer, selection, restore and recovery',async t=>{
 const {root,downloads}=setup(t),name='ШПИЛЕВОЙ ИЛЬЯ',replacement='СМИРНОВСКИЙ АЛЕКСАНДР';native.GlobalFonts.register(Buffer.from(fontBase64,'base64'),'FixturePdf');
 const art=native.createCanvas(500,300),context=art.getContext('2d');context.fillStyle='white';context.fillRect(0,0,500,300);context.fillStyle='black';context.font='22px FixturePdf';context.fillText(name,30,65);context.font='12px FixturePdf';context.fillText('UNCHANGED SUBTITLE',30,90);context.fillStyle='#e02040';context.fillRect(400,25,60,70);
 const doc=await PDFDocument.create();doc.registerFontkit(fontkit);const font=await doc.embedFont(Buffer.from(fontBase64,'base64'),{subset:true}),page=doc.addPage([500,300]);page.drawImage(await doc.embedPng(art.toBuffer('image/png')),{x:0,y:0,width:500,height:300});page.drawText(name,{x:30,y:235,size:22,font,opacity:0});page.drawText('UNCHANGED SUBTITLE',{x:30,y:210,size:12,font,opacity:0});const src=source('resume.pdf',await doc.save());
 let view=await mountSingleEditor(root,{source:src});t.after(()=>view.dispose());const item=view.drafts.left.entries().find(e=>e.text===name);await view.select(item.key,'left');root.querySelector('[data-pdf-text-view="left"]').click();const input=root.querySelector('[data-edit-side="left"]');input.value=replacement;input.dispatchEvent(new window.Event('input'));await until(()=>!root.querySelector('[data-save-side="left"]').disabled);root.querySelector('[data-pdf-preview="left"]').click();await until(()=>root.querySelector('.visual-scroll').getAttribute('aria-busy')==='false');assert.equal(root.querySelector('.pdf-export-state').textContent,'');assert.equal(root.querySelector('[data-save-side="left"]').dataset.pdfMode,'original');
 const parsed=await readTextSource(src),viewer=await openPdfVisual(src),blocks=await viewer.refineBlocks(parsed.blocks);await viewer.dispose();const [plan]=planPdfEdits([{block:blocks[0],text:replacement}],1,await measurePdfFont(),blocks);assert.equal(plan.autoFit,true);assert.ok(plan.size>=22*.8&&plan.size<=22);const hotspot=root.querySelector(`[data-group="${item.key}"]`);assert.ok(Math.abs(parseFloat(hotspot.style.width)-plan.width/5)<.01,'The selection includes the expanded text area');
 const checkpoint=validateSinglePayload({version:1,kind:'single-editor',source:src,sheet:null,delimiter:',',review:view.snapshot()});view.dispose();view=await mountSingleEditor(root,{source:src,restoredState:checkpoint.review});assert.deepEqual(view.snapshot().drafts,checkpoint.review.drafts,'Automatic fit does not create extra undo steps or explicit boxes');
 root.querySelector('[data-save-side="left"]').click();await until(()=>downloads.length===1);const output=source('out.pdf',new Uint8Array(await downloads.pop().arrayBuffer())),read=await readTextSource(output);assert.deepEqual(read.blocks.map(b=>b.text),[replacement,'UNCHANGED SUBTITLE']);const outViewer=await openPdfVisual(output),canvas=document.createElement('canvas');await outViewer.renderPage(1,canvas);assert.equal(outViewer.pageCount,1);await outViewer.dispose();const pixels=canvas.getContext('2d').getImageData(400,25,60,70).data;let red=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i]>190&&pixels[i+1]<60&&pixels[i+2]>40&&pixels[i+2]<100)red++;assert.ok(red>4000,'Nearby artwork is untouched');
 // A longer replacement still cannot cover nearby content; recovery opens its block directly.
 const edit=root.querySelector('[data-edit-side="left"]');edit.value=replacement.repeat(6);edit.dispatchEvent(new window.Event('input'));await until(()=>!root.querySelector('.pdf-recovery').hidden);assert.equal(root.querySelector('[data-save-side="left"]').disabled,true);root.querySelector('[data-pdf-adjust="left"]').click();await until(()=>root.querySelector('.pdf-block-dialog'));assert.equal(root.querySelector('.pdf-block-dialog textarea').value,replacement.repeat(6));root.querySelector('.pdf-block-actions .secondary').click();assert.equal(view.drafts.left.get(item.key),replacement.repeat(6));root.querySelector('[data-pdf-undo="left"]').click();await until(()=>!root.querySelector('[data-save-side="left"]').disabled);
 // Explicit extra room cannot overwrite the subtitle or colored artwork.
 const raw=await openPdfVisual(src);await assert.rejects(()=>raw.renderPage(1,document.createElement('canvas'),{edits:[{block:blocks[0],text:replacement,box:{width:460,height:60,fontSize:18}}],blocks}),/overlaps nearby text/);await raw.dispose();
 // Grouped A/B paragraphs retain every clickable line when just one line grows.
 view.dispose();const group={record:1,text:name+'\nUNCHANGED SUBTITLE',source_blocks:blocks},meta={name:src.name,format:'pdf'};
 view=await mountVisualReview(root,{sources:{left:src,right:src},report:{kind:'text',status:'complete',sources:{left:meta,right:meta},matched:[{key:'text:1',left:structuredClone(group),right:structuredClone(group)}]}});await view.select('text:1','left');const grouped=root.querySelector('[data-edit-side="left"]');grouped.value=replacement+'\nUNCHANGED SUBTITLE';grouped.dispatchEvent(new window.Event('input'));await until(()=>root.querySelector('.visual-pdf-page')?.dataset.pdfRevision===String(view.drafts.left.revision)&&root.querySelector('.visual-scroll').getAttribute('aria-busy')==='false');const targets=root.querySelectorAll('.visual-column')[0].querySelectorAll('[data-group="text:1"]');assert.equal(targets.length,2);assert.ok([...targets].some(n=>Math.abs(parseFloat(n.style.width)-plan.width/5)<.01));
});


function findUI(root){
 root.querySelector('.document-find>button').click();const panel=root.querySelector('.find-replace-panel');return {panel,query:panel.querySelector('[data-find-field="query"]'),replacement:panel.querySelector('[data-find-field="replacement"]'),button:label=>[...panel.querySelectorAll('button')].find(b=>b.textContent===label),async search(text){this.query.value=text;this.query.dispatchEvent(new window.Event('input'));await until(()=>!this.button('Replace').disabled);},setReplacement(text){this.replacement.value=text;this.replacement.dispatchEvent(new window.Event('input'));}};
}
test('Word find/replace preserves inserted table rows and autosaves one undoable batch',async t=>{
 const {root,downloads}=setup(t),demo=await readFile(new URL('../dist/document-demo.js',import.meta.url),'utf8'),src=JSON.parse(demo.slice(demo.indexOf('Object.freeze(')+14,demo.lastIndexOf(');'))).right;let saved,view;view=await mountSingleEditor(root,{source:src,onStateChange:()=>{saved=view.snapshot();}});t.after(()=>view.dispose());
 [...root.querySelectorAll('.visual-column:not([hidden]) [data-group]')].find(n=>n.textContent==='Desk lamp').click();root.querySelector('[data-row-side="left"][data-insert-row="after"]').click();const input=root.querySelector('[data-edit-side="left"]');input.value='Lamp and lamp';input.dispatchEvent(new window.Event('input'));input.dispatchEvent(new window.Event('blur'));const before=view.snapshot(),find=findUI(root);await find.search('lamp');assert.match(find.panel.querySelector('.find-replace-count').textContent,/of 3/);assert.ok(root.querySelector('.has-search-match'));find.setReplacement('Light');find.button('Replace all').click();await until(()=>/Replaced 3/.test(find.panel.textContent));
 const after=view.snapshot();assert.deepEqual(after.drafts.left.rowPlan,before.drafts.left.rowPlan);assert.deepEqual(after.drafts.right,before.drafts.right);assert.equal(after.drafts.left.history.length,before.drafts.left.history.length+1);assert.deepEqual(saved.drafts.left,after.drafts.left);assert.equal(after.drafts.left.entries.filter(e=>e.text.includes('Light')).length,2);find.button('Undo').click();await until(()=>!find.button('Replace').disabled);assert.deepEqual(view.drafts.left.entries(),before.drafts.left.entries);find.button('Replace all').click();await until(()=>/Replaced 3/.test(find.panel.textContent));
 root.querySelector('[data-save-side="left"]').click();await until(()=>downloads.length===1);const out=await readDocxVisual(source('edited.docx',new Uint8Array(await downloads.pop().arrayBuffer())));assert.ok(out.blocks.some(b=>b.text==='Light and Light'));
 view.dispose();view=await mountSingleEditor(root,{source:src,restoredState:after});root.querySelector('[aria-label="Undo edit"]').click();assert.deepEqual(view.snapshot().drafts.left.entries,before.drafts.left.entries);assert.deepEqual(view.snapshot().drafts.left.rowPlan,before.drafts.left.rowPlan);
 view.dispose();const parsed=await readTextSource(src);view=await mountVisualReview(root,{sources:{left:src,right:src},report:{kind:'text',status:'complete',sources:{left:parsed.meta,right:parsed.meta},matched:parsed.blocks.map(b=>({key:'text:'+b.record,left:b,right:structuredClone(b)}))}});const compare=findUI(root);assert.equal(compare.panel.querySelector('select').value,'right');await compare.search('Desk lamp');compare.setReplacement('Desk light');compare.button('Replace all').click();await until(()=>/Replaced 1/.test(compare.panel.textContent));assert.ok(view.drafts.left.text().includes('Desk lamp'));assert.ok(view.drafts.right.text().includes('Desk light'));const savedRight=view.drafts.right.snapshot();const scope=compare.panel.querySelector('select');scope.value='left';scope.dispatchEvent(new window.Event('change'));await until(()=>!compare.button('Replace').disabled);compare.setReplacement('Table lamp');compare.button('Replace').click();await until(()=>/Replaced 1/.test(compare.panel.textContent));assert.deepEqual(view.drafts.right.snapshot(),savedRight);assert.ok(view.drafts.left.text().includes('Table lamp'));
});
test('PDF find navigates pages, replaces one occurrence or all, preserves boxes and exports current text',async t=>{
 const {root,downloads}=setup(t),doc=await PDFDocument.create();doc.registerFontkit(fontkit);const font=await doc.embedFont(Buffer.from(fontBase64,'base64'),{subset:true});doc.addPage([400,500]).drawText('Alice Alice',{x:40,y:430,size:14,font});doc.addPage([400,500]).drawText('ALICE',{x:40,y:430,size:14,font});const src=source('names.pdf',await doc.save());let view=await mountSingleEditor(root,{source:src});t.after(()=>view.dispose());const first=view.drafts.left.entries()[0];view.drafts.left.replaceBlock(first.key,first.text,{width:180,height:30,fontSize:14});root.querySelector('[data-pdf-preview="left"]').click();await until(()=>!root.querySelector('[data-save-side="left"]').disabled);
 const find=findUI(root);await find.search('alice');assert.match(find.panel.querySelector('.find-replace-count').textContent,/1 of 3/);find.button('Next').click();await until(()=>!find.button('Replace').disabled);assert.equal(root.querySelector('[data-edit-side="left"]').selectionStart,6);find.button('Next').click();await until(()=>view.snapshot().pages.left===2&&!find.button('Replace').disabled);assert.equal(root.querySelector('[data-edit-side="left"]').value,'ALICE');
 find.setReplacement('Bob');find.button('Replace').click();await until(()=>/Replaced 1/.test(find.panel.textContent)&&!find.button('Replace').disabled);assert.equal(view.drafts.left.entries()[1].text,'Bob');assert.equal(view.drafts.left.entries()[0].text,'Alice Alice');const before=view.snapshot();find.button('Replace all').click();await until(()=>/Replaced 2/.test(find.panel.textContent)&&!root.querySelector('[data-save-side="left"]').disabled);const after=view.snapshot();assert.deepEqual(after.drafts.left.entries[0].pdfBox,before.drafts.left.entries[0].pdfBox);assert.equal(after.drafts.left.history.length,before.drafts.left.history.length+1);assert.equal(view.drafts.left.entries()[0].text,'Bob Bob');assert.equal(view.drafts.right.entries()[0].text,'Alice Alice');root.querySelector('[data-save-side="left"]').click();await until(()=>downloads.length===1);assert.equal(await textPdf(downloads.pop()),'Bob BobBob');
 view.dispose();view=await mountSingleEditor(root,{source:src,restoredState:after});root.querySelector('[aria-label="Undo edit"]').click();assert.deepEqual(view.drafts.left.entries(),before.drafts.left.entries);
 view.dispose();view=await mountSingleEditor(root,{source:src});await view.select(view.drafts.left.entries()[0].key,'left');const long=root.querySelector('[data-edit-side="left"]');long.value='Alice\n'.repeat(45)+'FINAL NEEDLE';long.dispatchEvent(new window.Event('input'));await until(()=>root.querySelector('[data-pdf-layout="updated"]'));const expanded=findUI(root);await expanded.search('NEEDLE');assert.ok(view.snapshot().pages.left>1,'A match near the end of expanded text opens its generated page');
 // An invalid pasted query stays local to the search panel and cannot interrupt autosave.
 expanded.query.value='x'.repeat(50001);expanded.query.dispatchEvent(new window.Event('input'));assert.match(expanded.panel.textContent,/shorter phrase/);assert.equal(expanded.button('Replace').disabled,true);
});

test('merged XLSX opens, edits anchors, undoes, restores and retains merges across grid pages and export',async t=>{
 const {root,downloads}=setup(t),book=utils.book_new(),ws=utils.aoa_to_sheet(Array.from({length:55},(_,r)=>[r?'Row '+(r+1):'Merged title',r>0?'Value '+(r+1):'',r>0?'Detail '+(r+1):'']));
 ws['!merges']=[utils.decode_range('A1:C1'),utils.decode_range('A3:A5'),utils.decode_range('B49:C52')];
 for(const address of ['A4','A5','C49','B50','C50','B51','C51','B52','C52'])delete ws[address];
 utils.book_append_sheet(book,ws,'Merged');const src=source('merged.xlsx',write(book,{type:'array',bookType:'xlsx',compression:true}));let view=await mountSingleEditor(root,{source:src,sheet:'Merged'});t.after(()=>view.dispose());
 assert.equal(root.querySelector('[data-cell="A1"]').parentElement.colSpan,3);assert.equal(root.querySelector('[data-cell="B1"]'),null);assert.equal(root.querySelector('[data-cell="A3"]').parentElement.rowSpan,3);
 root.querySelector('[data-cell="A1"]').click();root.querySelector('[data-edit-side="left"]').value='Updated merged title';root.querySelector('[data-apply-cell="left"]').click();assert.equal(root.querySelector('[data-cell="A1"]').textContent,'Updated merged title');
 root.querySelector('[data-sheet-undo]').click();assert.equal(root.querySelector('[data-cell="A1"]').textContent,'Merged title');
 root.querySelector('[data-edit-side="left"]').value='Saved merged title';root.querySelector('[data-apply-cell="left"]').click();const saved=view.snapshot();view.dispose();view=await mountSingleEditor(root,{source:src,sheet:'Merged',restoredState:saved});assert.equal(root.querySelector('[data-cell="A1"]').textContent,'Saved merged title');
 [...root.querySelectorAll('.visual-column:not([hidden]) button')].find(b=>b.textContent==='Next rows').click();assert.equal(root.querySelector('[data-cell="B49"]').parentElement.rowSpan,2);assert.equal(root.querySelector('[data-cell="C51"]'),null);assert.ok(root.querySelector('[data-cell="A51"]'));
 root.querySelector('[data-cell="B49"]').click();root.querySelector('[data-edit-side="left"]').value='Edited continuation';root.querySelector('[data-save-side="left"]').click();await until(()=>downloads.length===1);
 const result=read(new Uint8Array(await downloads[0].arrayBuffer()),{type:'array'}).Sheets.Merged;assert.deepEqual(result['!merges'],ws['!merges']);assert.equal(result.A1.v,'Saved merged title');assert.equal(result.B49.v,'Edited continuation');assert.equal(result.C51,undefined);
});
